import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import type { RepositoryKnowledgePackage } from "@openforge/shared";
import { RepositoryEvidenceExtractorService } from "../src/services/repository-evidence-extractor.service.js";
import { budgetAfterSafetyMargin, estimateTokens } from "../src/utils/token-estimator.js";
import { buildWorkspacePrompt } from "../src/services/workspace-prompt-builder.js";

const extractor=new RepositoryEvidenceExtractorService();
function knowledge(count=20):RepositoryKnowledgePackage {const paths=["README.md","pyproject.toml","fastf1/__init__.py","fastf1/core.py","tests/test_core.py",...Array.from({length:count},(_,i)=>`misc/file-${i}.py`)];return {repositoryId:"fastf1",fullName:"theOehrly/Fast-F1",provider:"github",defaultBranch:"main",generatedAt:"now",sourceLimits:{maxTreeEntries:999,maxFiles:999,maxFileBytes:999,maxTotalBytes:999,truncated:false},readme:{path:"README.md",content:"FastF1 Python telemetry library. ".repeat(200),sizeBytes:1000,truncated:false},tree:{totalEntries:paths.length,processedEntries:paths.length,truncated:false,directories:[{path:"fastf1",depth:1,category:"source",importance:"high"},{path:"misc",depth:1,category:"source",importance:"low"}],importantFiles:paths.map((path)=>({path,type:"blob",category:path.includes("test")?"test":"source",importance:path.startsWith("misc")?"low":"high",reason:path.startsWith("misc")?"miscellaneous":"architecture relevant"}))},detectedStack:{languages:["Python"],frameworks:[],packageManagers:["pip"],databases:[],testing:["pytest"],ci:["GitHub Actions"],deployment:[]},manifests:[{path:"pyproject.toml",kind:"python",contentPreview:"[project]\nname='fastf1'",parsed:{scripts:{fastf1:"fastf1:main"}}}],docs:{hasContributingGuide:true,hasCodeOfConduct:false,hasLicense:true,docFiles:["CONTRIBUTING.md"]},entryPoints:[{path:"fastf1/__init__.py",reason:"package entry"}],testStructure:{hasTests:true,testDirectories:["tests"],testFiles:["tests/test_core.py"],detectedFrameworks:["pytest"]},workflowFiles:[{path:".github/workflows/test.yml",name:"tests",contentPreview:"pytest"}],contributionReadiness:{score:80,level:"high",reasons:[],blockers:[]},complexity:{score:50,level:"intermediate",reasons:[]},raw:{selectedFilePaths:paths}};}
const identity={contextSnapshotId:"snapshot-1",headSha:"abc123"};

test("FastF1 Explorer evidence stays below budget and focuses on architecture",()=>{const p=extractor.extract(knowledge(150),"explorer",identity);assert.ok(p.estimatedTokensUsed<=p.tokenBudget);assert.ok(p.evidence.some((x)=>x.path==="pyproject.toml"));assert.ok(p.evidence.some((x)=>x.path==="fastf1/__init__.py"));});
test("large repositories obey item and token limits",()=>{const p=extractor.extract(knowledge(1000),"explorer",identity);assert.ok(p.evidence.length<=40);assert.ok(p.estimatedTokensUsed<=p.tokenBudget);});
test("Explorer excludes issues and commits",()=>{const p=extractor.extract(knowledge(),"explorer",identity,{collaboration:{issues:[{id:1}],commits:[{sha:"x"}]}});assert.ok(p.evidence.every((x)=>x.type!=="issue"&&x.type!=="commit"));});
test("Mission retains mission and related tests",()=>{const p=extractor.extract(knowledge(),"mission",identity,{activeMission:{issue:42,title:"Fix core telemetry"},selectedModule:"core telemetry"});assert.ok(p.evidence.some((x)=>x.type==="mission"));assert.ok(p.evidence.some((x)=>x.type==="test"));});
test("Mentor question retrieves matching evidence without unrelated files",()=>{const p=extractor.extract(knowledge(),"mentor",identity,{mentorQuestion:"How does fastf1 core telemetry work?"});assert.ok(p.evidence.some((x)=>x.path==="fastf1/core.py"));assert.ok(!p.evidence.some((x)=>x.path==="misc/file-0.py"));});
test("Timeline contains no raw source evidence",()=>{const p=extractor.extract(knowledge(),"timeline",identity,{timelineEvents:[{title:"Mission completed"}]});assert.ok(p.evidence.every((x)=>!["file","manifest","readme","workflow","test"].includes(x.type)));});
test("high-ranked evidence survives and low-ranked evidence is trimmed first",()=>{const p=extractor.extract(knowledge(1000),"timeline",identity,{timelineEvents:Array.from({length:100},(_,i)=>({i,text:"x".repeat(1000)}))});assert.equal(p.evidence[0]?.type,"repository_metadata");assert.ok(p.omittedEvidenceCount>0);});
test("token safety margin is applied",()=>assert.equal(budgetAfterSafetyMargin(2200,.15),1870));
test("empty repository has only identity evidence",()=>{const k=knowledge(0);k.readme={path:null,content:null,sizeBytes:0,truncated:false};k.tree.importantFiles=[];k.tree.directories=[];k.manifests=[];k.entryPoints=[];k.testStructure={hasTests:false,testDirectories:[],testFiles:[],detectedFrameworks:[]};k.workflowFiles=[];k.docs={hasContributingGuide:false,hasCodeOfConduct:false,hasLicense:false,docFiles:[]};const p=extractor.extract(k,"explorer",identity);assert.deepEqual(p.evidence.map((x)=>x.type),["repository_metadata"]);});
test("packages are repository and HEAD scoped",()=>{const a=extractor.extract(knowledge(),"explorer",identity);const k=knowledge();k.repositoryId="other";k.fullName="owner/other";const b=extractor.extract(k,"explorer",{...identity,headSha:"def456"});assert.notEqual(a.repositoryId,b.repositoryId);assert.notEqual(a.headSha,b.headSha);});
test("prompt builder accepts only evidence package and remains bounded",()=>{const p=extractor.extract(knowledge(150),"explorer",identity);const built=buildWorkspacePrompt(p,"prompt-v","content-v");assert.ok(built.estimatedTokens<=p.tokenBudget);assert.ok(estimateTokens(built.prompt)>0);assert.doesNotMatch(readFileSync(new URL("../src/services/workspace-prompt-builder.ts",import.meta.url),"utf8"),/RepositoryKnowledgePackage/);});
test("Workspace generation no longer serializes full repository knowledge",()=>{const source=readFileSync(new URL("../src/services/workspace-intelligence.service.ts",import.meta.url),"utf8");assert.doesNotMatch(source,/repositoryKnowledge:knowledge|recursiveTree|selectedSourceFiles/);assert.match(source,/buildWorkspacePrompt\(evidencePackage/);});
test("cache migration scopes packages and invalidates by HEAD",()=>{const sql=readFileSync(new URL("../../database/migrations/addon-10.sql",import.meta.url),"utf8");assert.match(sql,/user_id,repository_id,context_snapshot_id,module_type/);assert.match(sql,/head_sha/);assert.match(sql,/evidence_version/);assert.match(sql,/prompt_version/);});
