import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import type { RepositoryKnowledgePackage } from "@openforge/shared";
import { isLegacyGenericPayload, semanticContentHash, validateGeneratedPayload, WORKSPACE_CONTENT_VERSION } from "../src/services/workspace-grounding.js";
import { isActiveIngestionJobConflict } from "../src/services/workspace-intelligence.service.js";

function knowledge(paths:string[], fullName="owner/repo"):RepositoryKnowledgePackage { const readme=paths.find((p)=>/^readme/i.test(p))??null; return {repositoryId:"repo-1",fullName,provider:"github",defaultBranch:"main",generatedAt:"2026-01-01",sourceLimits:{maxTreeEntries:10,maxFiles:10,maxFileBytes:10,maxTotalBytes:10,truncated:false},readme:{path:readme,content:readme?"# Project":null,sizeBytes:readme?9:0,truncated:false},tree:{totalEntries:paths.length,processedEntries:paths.length,truncated:false,directories:[],importantFiles:paths.map((path)=>({path,type:"blob",category:"source",importance:"high",reason:"fixture"}))},detectedStack:{languages:[],frameworks:[],packageManagers:[],databases:[],testing:[],ci:[],deployment:[]},manifests:[],docs:{hasContributingGuide:false,hasCodeOfConduct:false,hasLicense:false,docFiles:[]},entryPoints:[],testStructure:{hasTests:false,testDirectories:[],testFiles:[],detectedFrameworks:[]},workflowFiles:[],contributionReadiness:{score:0,level:"low",reasons:[],blockers:[]},complexity:{score:0,level:"beginner",reasons:[]},raw:{selectedFilePaths:paths}}; }
const card=(title:string,path:string)=>({status:"ready",summary:"specific",cards:[{id:"one",title,summary:`About ${path}`,details:[],evidence:[{type:"file" as const,path,explanation:"Direct repository evidence"}]}]});

test("README-only content stays README-grounded",()=>{const result=validateGeneratedPayload(card("Project documentation","README.md"),knowledge(["README.md"]));assert.equal(result.cards[0]?.title,"Project documentation");assert.ok(!JSON.stringify(result).match(/Frontend|Backend|Services/));});
test("empty repository accepts no semantic cards",()=>{const result=validateGeneratedPayload({status:"insufficient_evidence",summary:"Insufficient evidence",cards:[]},knowledge([]));assert.equal(result.cards.length,0);});
test("cards with nonexistent paths are rejected",()=>assert.throws(()=>validateGeneratedPayload(card("Invented","missing.ts"),knowledge(["README.md"])),/nonexistent/));
test("all generated cards require evidence",()=>assert.throws(()=>validateGeneratedPayload({status:"ready",summary:"x",cards:[{id:"x",title:"x",summary:"x",details:[],evidence:[]}]},knowledge(["x.ts"]))));
test("unrelated repositories produce distinct semantic hashes",()=>assert.notEqual(semanticContentHash(card("OpenForge Workspace","frontend/app.tsx")),semanticContentHash(card("FastF1 telemetry","fastf1/core.py"))));
test("legacy generic packages and old versions are invalidated",()=>{assert.equal(isLegacyGenericPayload({cards:[],generationSource:"deterministic_fallback"}),true);assert.equal(WORKSPACE_CONTENT_VERSION,"workspace-modules-v3-groq-only");});
test("frontend modules do not build or fill semantic cards locally",()=>{for(const file of ["workspace-explorer.tsx","mission-engine.tsx","mentor-engine.tsx","review-engine.tsx","timeline-engine.tsx"]){const source=readFileSync(new URL(`../../frontend/components/workspace/${file}`,import.meta.url),"utf8");assert.doesNotMatch(source,/build(?:Concepts|Mission|Review|Journey)|DEFAULT_CARDS|fallbackList|Frontend|Backend|Authentication|Database|Services/);}});
test("renderer uses only returned cards and has an honest failure state",()=>{const source=readFileSync(new URL("../../frontend/components/workspace/generated-workspace-module.tsx",import.meta.url),"utf8");assert.match(source,/Array\.isArray\(payload\.cards\)/);assert.doesNotMatch(source,/DEFAULT_|FALLBACK_|generatedCards\.length\s*\?/);assert.match(source,/Groq generation is currently unavailable/);});
test("timeline renderer cannot create deterministic or fictional events",()=>{const source=readFileSync(new URL("../../frontend/components/workspace/timeline-engine.tsx",import.meta.url),"utf8");assert.doesNotMatch(source,/TimelineEvent|localStorage|createdAt|new Date/);});
test("concurrent active ingestion inserts are treated as an existing job",()=>{assert.equal(isActiveIngestionJobConflict({code:"23505",message:'duplicate key value violates unique constraint "idx_one_active_ingestion_job"'}),true);assert.equal(isActiveIngestionJobConflict({code:"23505",message:"another unique index"}),false);assert.equal(isActiveIngestionJobConflict({code:"42501",message:"permission denied"}),false);});
