import { env } from "../../config/env.js";
import { estimateTokens } from "../../utils/token-estimator.js";
import type { AIOrchestrationResult, AIOrchestrationTask, AIProviderAdapter } from "../providers/ai-provider.interface.js";
import { configuredModels } from "../providers/model-registry.js";
import { createProviderAdapters } from "../providers/provider-factory.js";
import { aiTaskRouterService, type AITaskRouterService } from "./ai-task-router.service.js";
import { providerHealthService, type ProviderHealthService } from "./provider-health.service.js";
export class AIOrchestratorService {private adapters:Map<string,AIProviderAdapter>;constructor(adapters:AIProviderAdapter[]=createProviderAdapters(),private router:AITaskRouterService=aiTaskRouterService,private health:ProviderHealthService=providerHealthService){this.adapters=new Map(adapters.map(a=>[a.providerId,a]));}
 async execute<T>(task:AIOrchestrationTask<T>):Promise<AIOrchestrationResult<T>>{const estimated=estimateTokens(`${task.system}\n${task.prompt}\n${task.schemaHint}`);const hardCeiling=Math.min(task.inputTokenBudget,env.AI_MAX_INPUT_TOKENS);if(estimated>hardCeiling)return {status:"unavailable",data:null,provider:null,model:null,attempts:0,fallbackUsed:false,errorCode:"input_token_budget_exceeded"};const ranked=this.router.rank(task,configuredModels(),estimated);const max=Math.min(task.maxAttempts??env.AI_MAX_PROVIDER_ATTEMPTS,ranked.length);let last="no_eligible_model";for(let index=0;index<max;index++){const candidate=ranked[index]!.model;const adapter=this.adapters.get(candidate.provider);if(!adapter)continue;try{console.info("AI orchestration task",{taskType:task.taskType,workspaceModule:task.workspaceModule,repositoryId:task.repositoryId,evidenceHash:task.evidenceHash,estimatedTokens:estimated,selectedProvider:candidate.provider,selectedModel:candidate.modelId,fallbackIndex:index});const result=await adapter.generateStructured({...task,model:candidate,maxOutputTokens:Math.min(task.outputTokenBudget,candidate.maxOutputTokens),timeoutMs:env.AI_TASK_TIMEOUT_MS});this.health.recordSuccess(candidate.provider,candidate.modelId);return {status:"completed",data:result.data,provider:result.provider,model:result.actualModel,attempts:index+1,fallbackUsed:index>0};}catch(error){const normalized=adapter.normalizeError(error);last=normalized.code;this.health.recordFailure(candidate.provider,candidate.modelId,normalized);if(normalized.code==="token_limit")continue;}}
 return {status:"unavailable",data:null,provider:null,model:null,attempts:max,fallbackUsed:max>1,errorCode:last};}
 diagnostics(){return {models:configuredModels().map(m=>({...m})),health:this.health.snapshot()};}}
export const aiOrchestratorService=new AIOrchestratorService();
