-- OpenForge addon-11: multi-provider AI orchestration registry, telemetry, cache and health.
create table if not exists public.ai_provider_models (id uuid primary key default gen_random_uuid(),provider text not null,model_id text not null,enabled boolean not null default true,reasoning_tier text not null check(reasoning_tier in ('fast','balanced','strong')),capabilities jsonb not null default '[]',context_window_tokens integer not null,recommended_input_tokens integer not null,max_output_tokens integer not null,supports_json_mode boolean not null default false,supports_json_schema boolean not null default false,private_repository_allowed boolean not null default false,priority integer not null default 0,status text not null default 'active',last_checked_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(provider,model_id));
create table if not exists public.ai_task_runs (id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,repository_id uuid references public.github_repositories(id) on delete cascade,workspace_module text,task_type text not null,provider text,model_id text,status text not null,input_token_estimate integer,input_tokens_actual integer,output_tokens_actual integer,latency_ms integer,fallback_index integer not null default 0,attempt_number integer not null default 1,error_code text,error_message text,evidence_hash text not null,prompt_version text not null,created_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists public.repository_evidence_summaries (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,repository_id uuid not null references public.github_repositories(id) on delete cascade,file_path text not null,blob_sha text not null,summary_type text not null,summary_payload jsonb not null,evidence_version integer not null,prompt_version text not null,provider text,model_id text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,repository_id,file_path,blob_sha,summary_type,prompt_version,evidence_version));
create table if not exists public.ai_provider_health (id uuid primary key default gen_random_uuid(),provider text not null,model_id text,status text not null,consecutive_failures integer not null default 0,cooldown_until timestamptz,last_error_code text,last_error_message text,last_checked_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(provider,model_id));
create index if not exists idx_ai_task_runs_repository on public.ai_task_runs(user_id,repository_id,created_at desc);create index if not exists idx_ai_task_runs_routing on public.ai_task_runs(provider,model_id,status,created_at desc);create index if not exists idx_evidence_summary_blob on public.repository_evidence_summaries(repository_id,blob_sha,summary_type);
alter table public.ai_task_runs enable row level security;alter table public.repository_evidence_summaries enable row level security;
drop policy if exists "Users read own AI task runs" on public.ai_task_runs;create policy "Users read own AI task runs" on public.ai_task_runs for select using(auth.uid()=user_id);
drop policy if exists "Users read own evidence summaries" on public.repository_evidence_summaries;create policy "Users read own evidence summaries" on public.repository_evidence_summaries for select using(auth.uid()=user_id);
create or replace function public.set_ai_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now();return new;end $$;
drop trigger if exists trg_ai_models_updated_at on public.ai_provider_models;create trigger trg_ai_models_updated_at before update on public.ai_provider_models for each row execute function public.set_ai_updated_at();
drop trigger if exists trg_ai_health_updated_at on public.ai_provider_health;create trigger trg_ai_health_updated_at before update on public.ai_provider_health for each row execute function public.set_ai_updated_at();
drop trigger if exists trg_evidence_summaries_updated_at on public.repository_evidence_summaries;create trigger trg_evidence_summaries_updated_at before update on public.repository_evidence_summaries for each row execute function public.set_ai_updated_at();
