import "dotenv/config";
import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  PORT: z.coerce.number().int().positive().default(4000),
  FRONTEND_URL: z.string().url().default("http://localhost:3000"),
  LOG_LEVEL: z.enum(["debug", "info", "warn", "error"]).default("info"),
  DATABASE_URL: z.string().optional(),
  SUPABASE_URL: z.string().optional(),
  SUPABASE_ANON_KEY: z.string().optional(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
  SUPABASE_JWT_SECRET: z.string().optional(),
  GITHUB_CLIENT_ID: z.string().optional(),
  GITHUB_CLIENT_SECRET: z.string().optional(),
  AI_PROVIDER: z.enum(["openai", "gemini", "groq", "ollama"]).default("groq"),
  AI_ORCHESTRATION_ENABLED: z.coerce.boolean().default(true),
  AI_ORCHESTRATION_MODE: z.enum(["multi_provider", "legacy"]).default("multi_provider"),
  AI_PROVIDER_PRIORITY: z.string().default("zai,nvidia,openrouter,openai"),
  AI_REQUIRE_STRUCTURED_OUTPUT: z.coerce.boolean().default(true),
  AI_DETERMINISTIC_FALLBACK: z.coerce.boolean().default(true),
  AI_MAX_PROVIDER_ATTEMPTS: z.coerce.number().int().positive().default(3),
  AI_TASK_TIMEOUT_MS: z.coerce.number().int().positive().default(60000),
  AI_RETRY_BASE_DELAY_MS: z.coerce.number().int().nonnegative().default(1500),
  AI_MAX_PARALLEL_TASKS: z.coerce.number().int().positive().default(4),
  AI_MAP_INPUT_TOKEN_BUDGET: z.coerce.number().int().positive().default(1200),
  AI_REDUCE_INPUT_TOKEN_BUDGET: z.coerce.number().int().positive().default(2200),
  AI_SYNTHESIS_INPUT_TOKEN_BUDGET: z.coerce.number().int().positive().default(3200),
  AI_VERIFICATION_INPUT_TOKEN_BUDGET: z.coerce.number().int().positive().default(1800),
  AI_MAP_MAX_OUTPUT_TOKENS: z.coerce.number().int().positive().default(700),
  AI_REDUCE_MAX_OUTPUT_TOKENS: z.coerce.number().int().positive().default(1200),
  AI_SYNTHESIS_MAX_OUTPUT_TOKENS: z.coerce.number().int().positive().default(2200),
  AI_VERIFICATION_MAX_OUTPUT_TOKENS: z.coerce.number().int().positive().default(700),
  AI_SUMMARY_BATCH_SIZE: z.coerce.number().int().positive().default(8),
  AI_MAX_SUMMARY_WORKERS: z.coerce.number().int().positive().default(3),
  AI_PROVIDER_COOLDOWN_SECONDS: z.coerce.number().int().positive().default(60),
  AI_RATE_LIMIT_BUFFER_PERCENT: z.coerce.number().min(0).max(99).default(20),
  AI_ORCHESTRATION_VERSION: z.coerce.number().int().positive().default(1),
  OPENAI_BASE_URL: z.string().url().default("https://api.openai.com/v1"),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_ENABLED: z.coerce.boolean().default(true),
  OPENAI_MODELS: z.string().optional(),
  OPENAI_DEFAULT_FAST_MODEL: z.string().optional(),
  OPENAI_DEFAULT_REASONING_MODEL: z.string().optional(),
  ZAI_ENABLED: z.coerce.boolean().default(true),
  ZAI_API_KEY: z.string().optional(),
  ZAI_BASE_URL: z.string().url().optional(),
  ZAI_MODELS: z.string().optional(),
  ZAI_DEFAULT_FAST_MODEL: z.string().optional(),
  ZAI_DEFAULT_REASONING_MODEL: z.string().optional(),
  NVIDIA_ENABLED: z.coerce.boolean().default(true),
  NVIDIA_API_KEY: z.string().optional(),
  NVIDIA_BASE_URL: z.string().url().default("https://integrate.api.nvidia.com/v1"),
  NVIDIA_MODELS: z.string().optional(),
  NVIDIA_DEFAULT_FAST_MODEL: z.string().optional(),
  NVIDIA_DEFAULT_REASONING_MODEL: z.string().optional(),
  OPENROUTER_ENABLED: z.coerce.boolean().default(true),
  OPENROUTER_API_KEY: z.string().optional(),
  OPENROUTER_BASE_URL: z.string().url().default("https://openrouter.ai/api/v1"),
  OPENROUTER_MODELS: z.string().optional(),
  OPENROUTER_USE_FREE_ROUTER: z.coerce.boolean().default(true),
  OPENROUTER_FREE_MODEL: z.string().default("openrouter/free"),
  OPENROUTER_FALLBACK_MODEL: z.string().optional(),
  GEMINI_API_KEY: z.string().optional(),
  GROQ_API_KEY: z.string().optional(),
  GROQ_BASE_URL: z.string().url().default("https://api.groq.com/openai/v1"),
  OLLAMA_BASE_URL: z.string().url().default("http://localhost:11434"),
  AI_DEFAULT_MODEL: z.string().optional(),
  AI_MAX_INPUT_TOKENS: z.coerce.number().int().positive().default(12000),
  AI_MAX_OUTPUT_TOKENS: z.coerce.number().int().positive().default(2000),
  WORKSPACE_JOB_TIMEOUT_SECONDS: z.coerce.number().int().positive().default(900),
  WORKSPACE_EXPLORER_INPUT_TOKEN_BUDGET: z.coerce.number().int().positive().default(2200),
  WORKSPACE_MISSION_INPUT_TOKEN_BUDGET: z.coerce.number().int().positive().default(2600),
  WORKSPACE_MENTOR_INPUT_TOKEN_BUDGET: z.coerce.number().int().positive().default(3000),
  WORKSPACE_REVIEW_INPUT_TOKEN_BUDGET: z.coerce.number().int().positive().default(2200),
  WORKSPACE_TIMELINE_INPUT_TOKEN_BUDGET: z.coerce.number().int().positive().default(1200),
  WORKSPACE_PROMPT_TOKEN_SAFETY_MARGIN: z.coerce.number().min(0).max(0.5).default(0.15),
  WORKSPACE_MAX_EVIDENCE_ITEMS: z.coerce.number().int().positive().default(40),
  WORKSPACE_MAX_EVIDENCE_ITEM_CHARS: z.coerce.number().int().positive().default(4000),
  WORKSPACE_MAX_PROMPT_CHARS: z.coerce.number().int().positive().default(24000),
  WORKSPACE_MAX_OUTPUT_TOKENS: z.coerce.number().int().positive().default(3000),
  REPOSITORY_EVIDENCE_VERSION: z.coerce.number().int().positive().default(1),
  REPO_CONTEXT_MAX_TREE_ENTRIES: z.coerce.number().int().positive().default(10000),
  REPO_CONTEXT_MAX_SELECTED_FILES: z.coerce.number().int().positive().default(150),
  REPO_CONTEXT_MAX_FILE_BYTES: z.coerce.number().int().positive().default(153600),
  REPO_CONTEXT_MAX_TOTAL_BYTES: z.coerce.number().int().positive().default(10485760),
  REPO_CONTEXT_MAX_README_BYTES: z.coerce.number().int().positive().default(153600),
  REPO_CONTEXT_MAX_COMMITS: z.coerce.number().int().positive().default(100),
  REPO_CONTEXT_MAX_ISSUES: z.coerce.number().int().positive().default(100),
  REPO_CONTEXT_MAX_PULL_REQUESTS: z.coerce.number().int().positive().default(100),
  REPO_CONTEXT_MAX_CONTRIBUTORS: z.coerce.number().int().positive().default(100),
  REPO_CONTEXT_MAX_RELEASES: z.coerce.number().int().positive().default(50),
  REPO_INTEL_MAX_TREE_ENTRIES: z.coerce.number().int().positive().default(3000),
  REPO_INTEL_MAX_FILES: z.coerce.number().int().positive().default(25),
  REPO_INTEL_MAX_FILE_BYTES: z.coerce.number().int().positive().default(80 * 1024),
  REPO_INTEL_MAX_TOTAL_BYTES: z.coerce.number().int().positive().default(500 * 1024),
  REPO_INTEL_MAX_README_BYTES: z.coerce.number().int().positive().default(80 * 1024)
});

const parsedEnv = envSchema.safeParse(process.env);

if (!parsedEnv.success) {
  console.error("Invalid backend environment configuration:");
  console.error(parsedEnv.error.flatten().fieldErrors);
  process.exit(1);
}

export const env = parsedEnv.data;
